server:
  port: 8090

spring:
  application:
    name: microservice-parking
  data:
    mongodb:
      uri: mongodb://admin:alcivar170816@localhost:27017/parkingDb?authSource=admin
      auto-index-creation: true

eureka:
  instance:
    hotHost: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/