server:
  port: 8080

spring:
  application:
    name: microservice-parking
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://admin:alcivar170816@localhost:27017/aparcamiento?authSource=admin

eureka:
  instance:
    hotHost: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/