server:
  port: 9090

spring:
  application:
    name: microservice-slot
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://admin:alcivar170816@localhost:27017/slotDb?authSource=admin

eureka:
  instance:
    hotHost: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/