server:
  port: 8090

spring:
  application:
    name: microservicio-plazas
  data:
    mongodb:
      uri: mongodb://localhost:27017/Aparcamientos

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka