server:
  port: 8080

spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: establecimientos
          uri: http://localhost:8090
          predicates:
            - Path=/api/establecimientos/**
        - id: plazas
          uri: http://localhost:8091
          predicates:
            - Path=/api/plazas/**
eureka:
  client:
    register-with-eureka: false